GET http://localhost:8080/api/products
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYyYmI2MTFiNzUzYzEzMzBiMWI2N2JmMyIsImZpcnN0TmFtZSI6Ik1hdGlhcyIsImxhc3ROYW1lIjoiU2lsdmEiLCJ1c2VyTmFtZSI6Ik1hNzdpdyIsImF2YXRhciI6Ii9zdGF0aWMvaW1nL0NWIERFViBFTkcucG5nIiwicGhvbmUiOiJkZmdkZmciLCJhZHJlc3MiOiIiLCJlbWFpbCI6Im1heGt2YWluQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiJDJiJDEwJE1uanYyZTNvaGFMS0h5b1pzQ1dWRWU1THVYVHUuZGFGOXZPeHlRdXRZLjZnQXhhNzJIeVZDIiwiY29uZmlybVBhc3N3b3JkIjoibSIsIl9fdiI6MH0sImlhdCI6MTY1NjgyODAyNCwiZXhwIjoxNjU2ODMxNjI0fQ.6A-Qsq8r1pMpvokbcQau0iaMQ-YXQhYfsLTNBgri9Lk