GET http://localhost:8080
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYyY2YxZGI1MzJjYjhiMDIyYmFhNWE0OCIsImZpcnN0TmFtZSI6InMiLCJsYXN0TmFtZSI6InMiLCJ1c2VyTmFtZSI6InMiLCJhdmF0YXIiOiIvc3RhdGljL2ltZy9pY29uLnBuZyIsInBob25lIjoicyIsImVtYWlsIjoicyIsInBhc3N3b3JkIjoiJDJiJDEwJHlqM2VGNkNYeUJFSG9IWGh4d1BZTk82SFg0UDA3emM1NEJ6VlVTLkouYzZCSG5oU0hEY1ouIiwiY29uZmlybVBhc3N3b3JkIjoicyIsIl9fdiI6MH0sImlhdCI6MTY1NzgyMTk2NCwiZXhwIjoxNjU3ODI1NTY0fQ.a6wif4sIYSrZx1ggZX5TZZ-nCCRAKyBQ3TGxoCd0osw
