GET http://localhost:8080/store
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYyYzczODVmMTk1YmI5MzU4YTdlZDZlZiIsImZpcnN0TmFtZSI6InMiLCJsYXN0TmFtZSI6InMiLCJ1c2VyTmFtZSI6InMiLCJhdmF0YXIiOiIvc3RhdGljL2ltZy9pY29uLnBuZyIsInBob25lIjoiMDkwOTA5MDkiLCJlbWFpbCI6InNAbCIsInBhc3N3b3JkIjoiJDJiJDEwJHJxdzFaaDUuUDk1Ni8yMTFST0thb2VEN0cub1NxU2FqM0gvOEl1YnF2V1JxRXgvd3VpNVRlIiwiY29uZmlybVBhc3N3b3JkIjoicyIsIl9fdiI6MH0sImlhdCI6MTY1NzU5MjUyNSwiZXhwIjoxNjU3NTk2MTI1fQ.yXb9ugwaW7BUhi0jlSRWrsKopfusOQECYRPh81eN2aY