GET http://localhost:8080/store
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYyYzQ4ZmNhOGRmMDg2NjkwMmY1OGZjOSIsImZpcnN0TmFtZSI6Ik1hdGlhcyIsImxhc3ROYW1lIjoiU2lsdmEiLCJ1c2VyTmFtZSI6Ik1hNzciLCJhdmF0YXIiOiIvc3RhdGljL2ltZy9pY29uLnBuZyIsInBob25lIjoiKzU5ODk5MDYzNzYxIiwiZW1haWwiOiJtYXhrdmFpbkBnbWFpbC5jb20iLCJwYXNzd29yZCI6IiQyYiQxMCQuNlR2WXNFUThudXQvTmZBNi5PSUMuUW9sLzk0THhWT2NwS2FnalpQWEI3MDk2MVp2UEVDNiIsImNvbmZpcm1QYXNzd29yZCI6InMiLCJfX3YiOjB9LCJpYXQiOjE2NTc1OTYwOTQsImV4cCI6MTY1NzU5OTY5NH0.Af5IGvvRJGWjm4cqg1VKCDOGEggPitaS3wevB6SHJn0